import { ArrowLeft, FileText, Calendar, Download, Printer, Home } from 'lucide-react';
import type { Property, MoveInReportType } from '../App';

type ReportViewProps = {
  report: MoveInReportType;
  property: Property;
  onBack: () => void;
};

export function ReportView({ report, property, onBack }: ReportViewProps) {
  // Download report as text file
  const downloadReport = () => {
    let content = `MOVE-IN REPORT\n`;
    content += `${'='.repeat(50)}\n\n`;
    content += `Property: ${property.propertyAddress}\n`;
    content += `Tenant: ${property.renterName}\n`;
    content += `Move-In Date: ${property.moveInDate ? new Date(property.moveInDate).toLocaleDateString() : 'N/A'}\n`;
    content += `Report Submitted: ${new Date(report.submittedAt).toLocaleDateString()}\n\n`;
    content += `${'='.repeat(50)}\n`;
    content += `ROOM CONDITIONS\n`;
    content += `${'='.repeat(50)}\n\n`;
    
    report.rooms.forEach((room, index) => {
      content += `${index + 1}. ${room.name}\n`;
      content += `   Condition: ${room.condition.toUpperCase()}\n`;
      if (room.notes) {
        content += `   Notes: ${room.notes}\n`;
      }
      content += `   Photos: ${room.photos.length} attached\n\n`;
    });
    
    content += `${'='.repeat(50)}\n`;
    content += `Generated by SewaSecure\n`;
    content += `Date: ${new Date().toLocaleDateString()}\n`;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `MoveIn-Report-${property.propertyAddress.replace(/[^a-zA-Z0-9]/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Print report
  const printReport = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50 pb-20 md:pb-8">
      {/* Header */}
      <header className="bg-gradient-to-r from-indigo-500 to-purple-600 shadow-lg print:bg-white print:border-b print:border-gray-200">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <button
            onClick={onBack}
            className="flex items-center gap-2 text-white hover:text-indigo-100 mb-4 print:hidden"
          >
            <ArrowLeft className="w-5 h-5" />
            Back to Reports
          </button>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="w-14 h-14 bg-white/20 backdrop-blur-sm rounded-xl flex items-center justify-center shadow-lg print:bg-indigo-100">
                <FileText className="w-8 h-8 text-white print:text-indigo-600" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-white print:text-gray-900">Move-In Report</h1>
                <p className="text-indigo-100 print:text-gray-600">{property.propertyAddress}</p>
              </div>
            </div>
            <div className="flex items-center gap-2 print:hidden">
              {/* Download Button */}
              <button
                onClick={downloadReport}
                className="flex items-center gap-2 px-4 py-2.5 bg-white/20 hover:bg-white/30 text-white rounded-lg transition-colors backdrop-blur-sm"
                title="Download as TXT"
              >
                <Download className="w-5 h-5" />
                <span className="hidden sm:inline">Download</span>
              </button>
              {/* Print Button */}
              <button
                onClick={printReport}
                className="flex items-center gap-2 px-4 py-2.5 bg-white/20 hover:bg-white/30 text-white rounded-lg transition-colors backdrop-blur-sm"
                title="Print Report"
              >
                <Printer className="w-5 h-5" />
                <span className="hidden sm:inline">Print</span>
              </button>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Property Info Card */}
        <div className="bg-white border border-gray-200 rounded-2xl p-6 mb-8 shadow-sm print:shadow-none">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            <div>
              <p className="text-sm text-gray-500 mb-1 flex items-center gap-2">
                <Home className="w-4 h-4" />
                Property Address
              </p>
              <p className="font-semibold text-gray-900">{property.propertyAddress}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500 mb-1">Tenant Name</p>
              <p className="font-semibold text-gray-900">{property.renterName}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500 mb-1 flex items-center gap-2">
                <Calendar className="w-4 h-4" />
                Move-In Date
              </p>
              <p className="font-semibold text-gray-900">
                {property.moveInDate 
                  ? new Date(property.moveInDate).toLocaleDateString('en-US', {
                      year: 'numeric',
                      month: 'long',
                      day: 'numeric'
                    })
                  : 'N/A'}
              </p>
            </div>
            <div>
              <p className="text-sm text-gray-500 mb-1">Report Submitted</p>
              <p className="font-semibold text-gray-900">
                {new Date(report.submittedAt).toLocaleDateString('en-US', {
                  year: 'numeric',
                  month: 'long',
                  day: 'numeric'
                })}
              </p>
            </div>
          </div>
        </div>

        {/* Summary Stats */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-8">
          <div className="bg-white border border-indigo-200 rounded-xl p-6 text-center shadow-sm">
            <p className="text-4xl font-bold text-indigo-600">{report.rooms.length}</p>
            <p className="text-sm text-gray-600 mt-2">Rooms Inspected</p>
          </div>
          <div className="bg-white border border-green-200 rounded-xl p-6 text-center shadow-sm">
            <p className="text-4xl font-bold text-green-600">
              {report.rooms.filter(r => r.condition === 'excellent' || r.condition === 'good').length}
            </p>
            <p className="text-sm text-gray-600 mt-2">Good Condition</p>
          </div>
          <div className="bg-white border border-yellow-200 rounded-xl p-6 text-center shadow-sm">
            <p className="text-4xl font-bold text-yellow-600">
              {report.rooms.filter(r => r.condition === 'fair').length}
            </p>
            <p className="text-sm text-gray-600 mt-2">Fair Condition</p>
          </div>
          <div className="bg-white border border-purple-200 rounded-xl p-6 text-center shadow-sm">
            <p className="text-4xl font-bold text-purple-600">
              {report.rooms.reduce((acc, r) => acc + r.photos.length, 0)}
            </p>
            <p className="text-sm text-gray-600 mt-2">Photos Attached</p>
          </div>
        </div>

        {/* Room Details */}
        <h2 className="text-2xl font-bold text-gray-900 mb-6">Room Conditions</h2>
        <div className="space-y-6">
          {report.rooms.map((room, index) => (
            <div key={index} className="bg-white border border-gray-200 rounded-2xl overflow-hidden shadow-sm print:break-inside-avoid">
              <div className="bg-gradient-to-r from-gray-50 to-gray-100 px-6 py-4 flex items-center justify-between border-b border-gray-200">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-indigo-500 rounded-lg flex items-center justify-center shadow-sm">
                    <span className="text-white font-bold text-lg">{index + 1}</span>
                  </div>
                  <h4 className="text-xl font-semibold text-gray-900">{room.name}</h4>
                </div>
                <span className={`px-4 py-2 rounded-full text-sm font-semibold capitalize shadow-sm ${
                  room.condition === 'excellent' ? 'bg-green-100 text-green-700 border border-green-200' :
                  room.condition === 'good' ? 'bg-blue-100 text-blue-700 border border-blue-200' :
                  room.condition === 'fair' ? 'bg-yellow-100 text-yellow-700 border border-yellow-200' :
                  room.condition === 'poor' ? 'bg-orange-100 text-orange-700 border border-orange-200' :
                  'bg-red-100 text-red-700 border border-red-200'
                }`}>
                  {room.condition}
                </span>
              </div>
              <div className="p-6">
                {room.notes && (
                  <div className="mb-6 p-4 bg-blue-50 rounded-xl border border-blue-200">
                    <p className="text-sm font-semibold text-blue-900 mb-2">Notes:</p>
                    <p className="text-gray-700 leading-relaxed">{room.notes}</p>
                  </div>
                )}
                {room.photos.length > 0 ? (
                  <div>
                    <p className="text-sm font-semibold text-gray-700 mb-4">
                      Photos ({room.photos.length})
                    </p>
                    <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
                      {room.photos.map((photo, photoIndex) => (
                        <div
                          key={photoIndex}
                          className="aspect-square rounded-xl overflow-hidden border-2 border-gray-200 hover:border-indigo-400 hover:shadow-lg transition-all group print:border print:border-gray-300"
                        >
                          <img
                            src={photo}
                            alt={`${room.name} photo ${photoIndex + 1}`}
                            className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                          />
                        </div>
                      ))}
                    </div>
                  </div>
                ) : (
                  <p className="text-gray-400 text-sm italic">No photos attached for this room</p>
                )}
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t border-gray-300 text-center">
          <div className="bg-white rounded-xl p-6 shadow-sm print:shadow-none">
            <p className="text-gray-600 mb-2">This report was generated by SewaSecure</p>
            <p className="text-sm text-gray-500">
              Report ID: {report.propertyId}-{new Date(report.submittedAt).getTime()}
            </p>
            <p className="text-sm text-gray-500 mt-1">
              Generated on {new Date().toLocaleDateString('en-US', {
                weekday: 'long',
                year: 'numeric',
                month: 'long',
                day: 'numeric'
              })}
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}

